config/routes.rb
Rails.application.routes.draw do
  #/
  root 'url_shorteners#index'

  resources :url_shorteners

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url_shortener.rb
class UrlShortener < ApplicationRecord
  before_save :generate_short_url, :sanitize_data

  def to_param
    self.short_url.to_s
  end

  private
    def generate_short_url
      self.short_url = SecureRandom.urlsafe_base64(3)
    end

    def sanitize_data
      unless self.long_url.include?("https") || self.long_url.include?("http")
        self.long_url = "https://#{self.long_url}"
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/url_shorteners_controller.rb
class UrlShortenersController < ApplicationController

  def index
    @url_shorteners = UrlShortener.all
  end

  def show
    @url_shortener = UrlShortener.find_by_short_url(params[:id])
    redirect_to @url_shortener.long_url
  end

  def new
    @url_shortener = UrlShortener.new
  end

  def create
    @url_shortener = UrlShortener.new(url_shortener_params)
    @url_shortener.save!
    redirect_to root_path
  end

  private
    def url_shortener_params
      params.require(:url_shortener).permit(:long_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/url_shorteners_helper.rb
module UrlShortenersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shortener</title>
    <%= csrf_meta_tags %>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/url_shorteners/index.html.erb
<h1 class="title">Wyncode ShortURLS</h1>

<% @url_shorteners.each do |us| %>
  <div class="">
    <label for="">Original Url</label>-<p><%= us.long_url %></p>

    <label for="">Short Url</label>-
    <!-- <a href="<%= url_shortener_url(us) %>"><%= us.short_url %></a> -->
    <%= link_to us.short_url, us %>
  </div>
  <hr>
<% end %>

<%= link_to "New Shortener", new_url_shortener_path, class: "btn btn-primary" %>

app/views/url_shorteners/new.html.erb
<%= form_for @url_shortener do |f| %>
  <div class="submit-center">
    <%= f.label(:long_url) %>
    <%= f.text_field :long_url %>

    <%= f.submit "Create", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/url_shorteners/show.html.erb
<h1>UrlShorteners#show</h1>
<p>Find me in app/views/url_shorteners/show.html.erb</p>